version: "3.8"                                  # 파일 규격 버전
services:                                       # 실행하려는 컨테이너들을 정의
  selenium-lottery-purchaser:                   # 서비스명
    container_name: selenium-lottery-purchaser  # 컨테이너 명
    build:
      dockerfile: Dockerfile
      context: ./selenium
    image: pyo92/selenium-lottery-purchaser
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 256mb
    environment:
      - SE_SCREEN_WIDTH=1024
      - SE_SCREEN_HEIGHT=768
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_SESSION_TIMEOUT=60
    ports:
      - "4445:4444"                             # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
      - "5901:5900"
      - "7901:7900"
  app-lottery-purchaser:
    container_name: app-lottery-purchaser
    build: .
    depends_on:                                 # 타 컨테이너가 실행된 다음 app 컨테이너 실행되도록 설정
      - selenium-lottery-purchaser
    image: pyo92/app-lottery-purchaser
    environment:                                # env 파일에서 환경변수 주입
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SELENIUM_HUB_URL=${SELENIUM_HUB_URL}
      - SELENIUM_RETRY_CNT=${SELENIUM_RETRY_CNT}
    ports:
      - "80:8080"
    restart: always                             # 컨테이너 실행 실패하는 경우 재시작할 수 있도록 설정
